server:
  port: 8081
spring:
  application:
    name: PalmLife
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.163.134:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.163.134
    port: 6379
    password: 123456

    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.PalmLife.entity # 别名扫描包
logging:
  level:
    com.PalmLife: debug
    org.redisson: DEBUG